### PR TITLE
Fix removal description of not shared sensor

### LINKED ISSUE #1913: User signed out and signed in to another account sensor delete menu shows wrong text
Description:

User signed out from Ruuvi Station and signed in to another account, then added sensor to Ruuvi Station.
In Delete Sensor page he now sees text that this sensor was shared to him, but this is not true.

https://github.com/ruuvi/com.ruuvi.station.ios/assets/50437378/85d6da32-6bc8-4f42-8aac-ae0b71bad8cb

### PR DESCRIPTION
**Pull request by rinat-enikeev**
Previousely shared was determined by just `shared: !ruuviTag.isOwner`. This is obviousely incorrect, so I added ownership enum. Fixes #1913

### CODE REVIEW

**Review by priyonto — APPROVED** [review]

File: Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/Removal/View/UI/SensorRemovalViewController.swift [hunk 1]
```diff
@@ -92,26 +92,24 @@ extension SensorRemovalViewController: SensorRemovalViewInput {
...
+        case .sharedWithMe:
+            messageLabel.text = RuuviLocalization.removeSharedSensorDescription
+            removeButtonConstraintClaimedSensor.isActive = false
+            removeButtonConstraintOtherSensor.isActive = true
+            removeCloudHistoryActionContainer.isHidden = true
+        case .locallyAddedButNotMine, .locallyAddedAndNotClaimed:
+            messageLabel.text = RuuviLocalization.removeLocalSensorDescription
+            removeButtonConstraintClaimedSensor.isActive = false
+            removeButtonConstraintOtherSensor.isActive = true
+            removeCloudHistoryActionContainer.isHidden = true
```
Comment (priyonto) [inline Apps/RuuviStation/Sources/Classes/Presentation/Modules/TagSettings/Submodules/Removal/View/UI/SensorRemovalViewController.swift:111]: Minor of course, but I would simplify the constraints and visibility of the container to single lines instead of having it in all cases.

**Review by priyonto — APPROVED** [review]
Nice fix :)
