### PR TITLE
Fix signed in initial empty screen (#1829)

### LINKED ISSUE #1828: Avoid showing "Sign In" prompt if user has zero sensors and is logged in
Steps: 
1. User has zero sensors
2. User logs in

Expected: 
+

Actual: 
- prompt to sign in

### PR DESCRIPTION
**Pull request by rinat-enikeev**
fixes #1828

### CODE REVIEW

File: Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/View/NoSensorView.swift [hunk 1]
```diff
@@ -130,13 +130,14 @@ extension NoSensorView {
...
+        let buttons = userSignInOnce ? [addSensorButton] : [signInButton, addSensorButton]
         for button in buttons {
             centerButtonStackView.addArrangedSubview(button)
         }
         messageLabel.text = userSignInOnce ?
-            RuuviLocalization.dashboardNoSensorsMessageSignedOut :
-            RuuviLocalization.dashboardNoSensorsMessage
+            RuuviLocalization.dashboardNoSensorsMessage :
+            RuuviLocalization.dashboardNoSensorsMessageSignedOut
+
```
Comment (priyonto) [inline Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/View/NoSensorView.swift:140]: This changes the behaviour expected on card https://github.com/ruuvi/com.ruuvi.station.ios/issues/1634

We need to check `userSignInOnce` and current logged in state here. `userSignInOnce` indicates whether user signed in past on the app, but not whether he/she is currently logged in. We should hide the sign in button only if user is logged in.

**Review by priyonto — COMMENTED** [review]
This needs checking.

File: Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/View/NoSensorView.swift (hunk 1 above)
Comment (rinat-enikeev) [reply Apps/RuuviStation/Sources/Classes/Presentation/Modules/Dashboard/Home/View/NoSensorView.swift:140]: thanks, did with respect to spec here https://github.com/ruuvi/com.ruuvi.station.ios/pull/1831
